:sectanchors:
:toc: macro
:toclevels: 2
:toc-title: Table of Content
:numbered:

= Fuse For Practitioners

toc::[]

== Pre-Requisites

- JDK 8
- Apache Maven >= 3.2.5
- JBDS 8 or 9 + Fuse Tooling ?
- JBoss Fuse 6.2.1

== Introduction

The goal of this project is to provide use cases / problems to be resolved by the students, practitioners during a lab session. This page lists the uses cases available and provides for each use case

- a description of the problem to be resolved,
- the technologies involved,
- the time estimated to design the solution and
- the criteria to be used to evaluate the students

At the beginning of each day, a short presentation of the use cases/problems to resolve (= to be developed) will be presented. Next, the students will start to work on their project. They will submit to the teacher the solution to be evaluated.
A git repository will be created for the purposes of the bootcamp with a branch / user. Ideally, the evaluation results should be next discussed/challenged with the  Enterprise Integration Practice Leader to determine the next steps.

== Use Case 0 : Camel Routes with HL7 DataFormat & A-MQ

* Description

The business use-case is an emergency master patient index for different heatlh-care providers to exchange patient information.

An HL7 message carrying patient demographic information is received by the business process, validated, transformed and sent to the Nextgate web service to add the patient information, if needed. In this part of the usecase, the intent is to develop 3 different components to accomplish this.

Active MQ can be used to separate different aspects of this flow so as to have flexibility of hosting these different routes and also be able to scale the producers and consumers of data.

Another design pattern followed is the use of the properties file to encode URLs and other connection information as opposed to hard-coding.

Message traceability is managed by using XML. For that reason, convert to XML before dropping it on the queue.

* Time estimated : ?
* How to evaluate the solution of the student : ?

== Use Case 1 : Camel Route with CSV/Bindy Dataformat & DataMapper Tool to transform the Java objects

* Description

The purpose of the use case is to develop some Apache Camel pipeline routes where we will process CSV files, read the CSV records and transform the records to Java Objects.
Next, we will split the List of the Java Objects to enhance each Java Object using the JBoss Fuse Data Mapper tool. The java object enhanced will be finally transformed into a JSON String that you will
save into a file.

The DLQ pattern must be implemented to move the "erroneous" CSV records into an error folder (using Exception Strategy and DLQErrorHandler).

The project to be developed must contain a unit test to test the data transformations of the CSV message to JSON.

* Time estimated : 1h30 - 2h
* How to evaluate the solution of the student :
- Review the Apache Camel Route created and how it has been designed to split the content and handle the exception (= DLQ pattern)
- Check that the Unit Test Class extend CamelSpringTestSupport class, include a ProducerTemplate, a MockEndpoint and that 2 assertions conditions have been added to test that
  we have a result (expectedMessageCount) and that the body correspond to the JSon String expected (expectedBodiesReceived).

== Use Case 2 : Camel Route aggregating messages enriched and transformed from REST & WebServices endpoints

* Description

Process the JSON files generated by the use case 1, send each JSON Object to a REST endpoint responsible to enrich the message and a Web Service responsible to transform the result returned in XML format.
Aggregate the responses received and take care about the transformation XML/JSon. Publish the result into a H2 DB using the SQL/JDBC component. The definition of the WSDL, JSON files, WebService, REST Service & DB will be provided.

* Time estimated : 4h - 5h
* How to evaluate the solution of the student :
- Review the Apache Camel Route created and how it has been designed to expose the REST/WebService, aggregate the content and insert the records into a database
- Check that the aggregated Account created correspond to what is described within the problem introduction
- Review the unit test

== Use Case 3 : Camel Route publishing the messages into a queue and handling the DLQ messages

* Description

The purpose of this use case is to extend/revisit the use case 1 to publish the JSON messages into different queues instead of the folders outbox and error.
For the erroneous messages, you will replace the DLQ folder with a DLQ queue and will develop a strategy to update/correct the erroneous messages
and re inject these messages into the normal flow. A redelivery policy must be put in place to avoid that the client, through the connection factory
, tries to redeliver the erroneous message.

A notification/alert mechanism must be developed to send a message to a topic containing the error code and error message. To be notified that there is an error,
an interception strategy must be defined to check if there is an IllegalArgumentException generated. If this is case, an error code and the exception message will
be added to the message that you will publish on a topic.
A client is connected to this topic in order to be informed about the error reported when a faulty exception is thrown. The erroneous message and the message code
received will be saved into an error table. Each record created will be managed with a status (ERROR, FIXED, CLOSE).
According to the strategy that you have developed to correct the message, you will next resend/republish it to the queue consuming
the input messages in order to process it if the status value is equal to FIXED. The messages consuled from the database will have finally their status updated to the value CLOSE.

* Time estimated : 2h
* How to evaluate the solution of the student :
- Review the Apache Camel Routes created to manage the messages into the queues (input, error and output)
- Verify that the faulty message is not redelivered and well saved into the DLQ.usecase-inout queue
- Challenge the strategy developed by the student to correct the messages and reinject them within the input queue
- Review the JMS/ActiveMQ components, how they are configured to access the Broker
- Control that theJMS TxManager is used

== Use Case 4 : Authenticate and authorize the access to the A-MQ broker using a LDAP server

* Description

Based on the previous use case, you will now secure the access to the A-MQ Broker using the JAAS LDAP module and a LDAP server (Apache DS). 2 users will be created (admin, jdoe) and
they will be associated to different roles (admin, write & read) in order to manage using the authorization plugin the operation they could perform on the queues; create, publish or read.

* Time estimated : 2-3h
* How to evaluate the solution of the student :
- Review the LDIF file created to secure, restrict access to the A-MQ broker
- Check the A-MQ Broker configuration to authenticate/authorize the user accessing the LDAP server
- Review the jUnit Test case developed and controlling how a user can write or not to a queue if he/she the grants to perform such operation

== Use Case 5 : xxxx

* Description

Distribute the workload of the JSON messages published into a queue using either concurrentClient defined into a camel route or either by deploying the camel route used as client into multiple JVM.
The camel routes could be deployed into different JBoss Fuse containers or locally.

* Time estimated : ?
* How to evaluate the solution of the student : ?

== Use Case 6 : xxxx

* Description

Based on the use case 2 code, implement the request/reply pattern between the REST Service and a backend system responsible to enrich the message.
In case of timeout or no response received, return a json message with an error code.

* Time estimated : ?
* How to evaluate the solution of the student : ?

== Use Case 7 : xxxx

* Description

Develop the OSGI Services exposing the Services used by the Camel Beans of the use Case 1 to enhance, validate the the messages designed within the use case 1.
Extend the camel routes with a REST service deployed into another bundle and responsible to generate the enhanced message after calling the OSGI Service.
Externalize the Camel endpoints properties using OSGI Config Admin & Properties placeholder.

* Time estimated : ?
* How to evaluate the solution of the student : ?

== Use Case 8 : xxxx

* Description

Develop a pax-exam integration test to validate the java to java transformation of the use case 1.
Package the project of the use case 7 using a features XML file and deploy it on JBoss Fuse

* Time estimated : ?
* How to evaluate the solution of the student : ?

== Use Case 9 : xxxx

* Description

Develop the required profiles to deploy the Use case 8 project into some JBoss Fuse Containers.
Implement a project to update and rollback the project.
Repackage your project of the use case 2 to be deployed using some profiles on JBoss Fuse Fabric

* Time estimated : ?
* How to evaluate the solution of the student : ?

== Use Case 10 : xxxx

* Description

Use insight technology to monitor the Camel Routes and collect the Camel metrics of the use case 7.
Develop a Camel route able to query the Elasticsearch server to fetch the info saved by the insight modules (log, metrics, ...).

* Time estimated : ?
* How to evaluate the solution of the student : ?

== Use Case 11  : xxxx

* Description

Develop a simple BAM solution using a Camel interceptor to save the business info collected from the routes of the use case 7 within a H2 database and create a camel route generating every 1 hour a report file (CSV) with the business info collected

* Time estimated : ?
* How to evaluate the solution of the student : ?

== Use Case 12 : xxxx

* Description

Create a json dashboard (http://www.hawkular.org/) displaying the status of the camel routes, endpoints, ... using the jolokia servlet

* Time estimated : ?
* How to evaluate the solution of the student : ?

== Use Case 13 : xxxx

* Description

TBD. Fabric based endpoint indirection for Camel routes & Fabric Discovery URL based brokers (optional).

* Time estimated : ?
* How to evaluate the solution of the student : ?


