:sectanchors:
:toc: macro
:toclevels: 2
:toc-title: Table of Content
:numbered:

== Fuse For Practitioners


At the beginning of each day, a short presentation of the use cases/problems to resolve (= to be developed) will be presented. Next, the students will start to work on their project. They will submit to the teacher the solution to be evaluated.
A git repository will be created for the purposes of the bootcamp with a branch / user. Ideally, the evaluation results should be next discussed/challenged with the  Enterprise Integration Practice Leader to determine the next steps.


=== Use Case 0

* Name : Camel Routes with HL7 DataFormat & A-MQ
* Description

The business use-case is an emergency master patient index for different heatlh-care providers to exchange patient information.

An HL7 message carrying patient demographic information is received by the business process, validated, transformed and sent to the Nextgate web service to add the patient information, if needed. In this part of the usecase, the intent is to develop 3 different components to accomplish this.

Active MQ can be used to separate different aspects of this flow so as to have flexibility of hosting these different routes and also be able to scale the producers and consumers of data.

Another design pattern followed is the use of the properties file to encode URLs and other connection information as opposed to hard-coding.

Message traceability is managed by using XML. For that reason, convert to XML before dropping it on the queue.

* Time estimated : ?
* How to evaluate the solution of the student : ?

=== Use Case 1
* Description

Process CSV files, data transform the records to Java Objects, Split the content, enhance the content (using the Data Mapper tool) and convert the objects to JSON file to be saved into individual files. The DLQ pattern must be implemented to move the "erroneous" CSV records into an error folder (using Exception Strategy and DLQErrorHandler).
The project to be developed must contain the unit tests to test the data transformations of the message

=== Use Case 2
## Description
Process the JSON files generated by the use case 1, send each JSON Object to a REST endpoint responsible to enrich the message and also a Web Service responsible to transform the result returned in XML format. Aggregate the responses received and publish the result into a H2 DB using the SQL/JDBC component. The definition of the WSDL, JSON files, WebService, REST Service & DB will be provided.

=== Use Case 3
## Description
Extend the use case 1 to publish the JSON messages into a queue instead of a folder. Replace the DLQ folder with a DLQ queue. Develop a strategy to update/correct the erroneous messages and re inject these messages into the normal flow

=== Use Case 4
## Description 
Based on the previous used case, you will now secure the A-MQBroker using the JAAS LDAP module and a LDAP server (Apache DS).
3 roles will be created (admin, write & read) to restrict the access and manageament of the users on the broker

=== Use Case 5
## Description
Distribute the workload of the JSON messages published into a queue using either concurrentClient defined into a camel route or either by deploying the camel route used as client into multiple JVM. The camel routes could be deployed into different JBoss Fuse containers or locally

=== Use Case 6
## Description 
Based on the use case 2 code, implement the request/reply pattern between the REST Service and a backend system responsible to enrich the message. In case of timeout or no response received, return a json message with an error code.

=== Use Case 7
## Description
Develop the OSGI Services exposing the Services used by the Camel Beans of the use Case 1 to enhance, validate the the messages designed within the use case 1. Extend the camel routes with a REST service deployed into another bundle and responsible to generate the enhanced message after calling the OSGI Service. Externalize the Camel endpoints properties using OSGI Config Admin & Properties placeholder.

=== Use Case 8
## Description
Develop a pax-exam integration test to validate the java to java transformation of the use case 1. Package the project of the use case 7 using a features XML file and deploy it on JBoss Fuse

=== Use Case 9
## Description
Develop the required profiles to deploy the Use case 8 project into some JBoss Fuse Containers. Implement a project to update and rollback the project. Repackage your project of the use case 2 to be deployed using some profiles on JBoss Fuse Fabric

=== Use Case 10
## Description
Use insight technology to monitor the Camel Routes and collect the Camel metrics of the use case 7. Develop a Camel route able to query the Elasticsearch server to fetch the info saved by the insight modules (log, metrics, ...).

=== Use Case 11
## Description
Develop a simple BAM solution using a Camel interceptor to save the business info collected from the routes of the use case 7 within a H2 database and create a camel route generating every 1 hour a report file (CSV) with the business info collected

=== Use Case 12
## Description
Create a json dashboard (http://www.hawkular.org/) displaying the status of the camel routes, endpoints, ... using the jolokia servlet

=== Use Case 13
## Description
TBD. Fabric based endpoint indirection for Camel routes & Fabric Discovery URL based brokers (optional).


