:scrollbar:
:data-uri:

== Xlate Use-Case Lab

.Goals
Receive the Person object on A-MQ and publish the ExecuteMatchUpdate XML on A-MQ

:numbered:

== Develop the Xlate application

=== Consume the message from A-MQ
* Consumes the Person XML from an ActiveMQ Queue (q.empi.deim.in)

=== Unmarshal the XML to a Java object
* Converts the Person XML to a Person Object 

=== Typeconvert to a class that matches ExecuteMatchUpdate
* Converts the Person Object to an ExecuteMatchUpdate Object, which is the operation on the web service. To accomplish this, you have to write your own TypeConverter with the convertTo method implemented. The parameters to this method are as follows:
- Type is the type of the object you want to convert to
- the Exchange is passed in and executing a getIn() or getBody() will return a Person object that can be copied into the Object. 
- Object: object you want to convert to. 

=== Marshal to XML
* Converts the ExecuteMatchUpdate Object to ExecuteMatchUpdate XML

=== Publish to A-MQ
* Dispatches the ExecuteMatchUpdate  XML to an ActiveMQ Queue (q.empi.nextgate.out)

=== Build the `Xlate` Project
. On the command line, run the following commands:
* mvn clean install
* mvn camel:run


