:scrollbar:
:data-uri:

== Outbound Use-Case Lab

.Goals
* Receive the ExecuteMatchUpdate class from A-MQ. Nextgate web-service will be provided for testing. You will invoke ExecuteMatchUpdate against the server. Respond back to the client using the Done transformer

:numbered:

== Develop the Outbound application

=== Consume the message from A-MQ
* Consumes the ExecuteMatchUpdate XML from an ActiveMQ Queue (q.empi.nextgate.out) 

=== Marshal the Java object to XML
* Converts the ExecuteMatchUpdate XML to a ExecuteMatchUpdate Object

=== Invoke the Nextgate web service

* Use the ExecuteMatchUpdate Object to build the Nextgate WebService Request (sent to WebService) 
* Dispatches the request to the Nextgate Service URI - CXF_WS_ENDPOINT_URI Input is the WSDL for the webservice. 

=== Develop the JUnit Tests

Develop a feature and a fabric profile. Test using SOAPUI or curl. 

=== Build the `Outbound` Project
. On the command line, run the following commands:
* mvn clean install
* mvn camel:run

